# Read V1DD datasets with `DatasetReader`

This notebook demonstrates dataset discovery and wide reads for the V1DD release 1196 proofread axon and dendrite cohorts.

In [1]:
from pathlib import Path

import polars as pl

from connects_common_connectivity.io import DatasetReader

In [2]:
DATASET_ROOT = Path("../results/v1dd_1196_v3")
AXON_DATASET = "v1dd_1196_proofread_axons"
DENDRITE_DATASET = "v1dd_1196_proofread_dendrites"

reader = DatasetReader(DATASET_ROOT)

## Available datasets

In [3]:
reader.display_dataset_names()

shape: (3, 4)
┌───────────────────────────────┬───────────────────────────────┬────────────┬─────────────────────┐
│ id                            ┆ name                          ┆ project_id ┆ modality            │
│ ---                           ┆ ---                           ┆ ---        ┆ ---                 │
│ str                           ┆ str                           ┆ str        ┆ str                 │
╞═══════════════════════════════╪═══════════════════════════════╪════════════╪═════════════════════╡
│ v1dd_1196_em                  ┆ V1DD release 1196 — EM somas  ┆ v1dd       ┆ ELECTRON_MICROSCOPY │
│ v1dd_1196_proofread_axons     ┆ V1DD release 1196 — proofread ┆ v1dd       ┆ ELECTRON_MICROSCOPY │
│                               ┆ …                             ┆            ┆                     │
│ v1dd_1196_proofread_dendrites ┆ V1DD release 1196 — proofread ┆ v1dd       ┆ ELECTRON_MICROSCOPY │
│                               ┆ …                             ┆            ┆                     │
└───────────────────────────────┴───────────────────────────────┴────────────┴─────────────────────┘

## Related feature sets and cluster sets

In [7]:
for dataset_name in (AXON_DATASET, DENDRITE_DATASET):
    print(dataset_name)
    display(reader.display_featuresets(dataset_name))
    display(reader.display_clustersets(dataset_name))
    print('\n\n\n\n')

v1dd_1196_proofread_axons

shape: (2, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ feature_set_id ┆ matrix_id      ┆ description    ┆ extraction_me ┆ feature_defin ┆ cell_index_co │
│ ---            ┆ ---            ┆ ---            ┆ thod          ┆ ition_ids     ┆ lumn          │
│ str            ┆ str            ┆ str            ┆ ---           ┆ ---           ┆ ---           │
│                ┆                ┆                ┆ str           ┆ list[str]     ┆ str           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ v1dd_soma_feat ┆ v1dd_v1dd_soma ┆ V1DD soma      ┆ Loaded from   ┆ ["nucleus_vol ┆ id            │
│ ures           ┆ _features      ┆ morphology and ┆ v1dd_v1196    ┆ ume_um",      ┆               │
│                ┆                ┆ nucle…         ┆ soma_fe…      ┆ "nucleus…     ┆               │
│ v1dd_soma_spat ┆ v1dd_v1dd_soma ┆ Soma spatial   ┆ Queried from  ┆ ["soma_voxel_ ┆ id            │
│ ial            ┆ _spatial       ┆ features for   ┆ CAVE nucleus  ┆ x", "soma_vox ┆               │
│                ┆                ┆ V1DD…          ┆ tabl…         ┆ el_y…         ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

shape: (1, 4)
┌─────────────────┬───────────────────────────┬────────┬──────────────────────────┐
│ clusterset_id   ┆ run                       ┆ root   ┆ clusters                 │
│ ---             ┆ ---                       ┆ ---    ┆ ---                      │
│ str             ┆ str                       ┆ str    ┆ list[str]                │
╞═════════════════╪═══════════════════════════╪════════╪══════════════════════════╡
│ v1dd_cell_types ┆ v1dd_cell_type_annotation ┆ neuron ┆ ["neuron", "E", … "STC"] │
└─────────────────┴───────────────────────────┴────────┴──────────────────────────┘

v1dd_1196_proofread_dendrites

shape: (2, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ feature_set_id ┆ matrix_id      ┆ description    ┆ extraction_me ┆ feature_defin ┆ cell_index_co │
│ ---            ┆ ---            ┆ ---            ┆ thod          ┆ ition_ids     ┆ lumn          │
│ str            ┆ str            ┆ str            ┆ ---           ┆ ---           ┆ ---           │
│                ┆                ┆                ┆ str           ┆ list[str]     ┆ str           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ v1dd_soma_feat ┆ v1dd_v1dd_soma ┆ V1DD soma      ┆ Loaded from   ┆ ["nucleus_vol ┆ id            │
│ ures           ┆ _features      ┆ morphology and ┆ v1dd_v1196    ┆ ume_um",      ┆               │
│                ┆                ┆ nucle…         ┆ soma_fe…      ┆ "nucleus…     ┆               │
│ v1dd_soma_spat ┆ v1dd_v1dd_soma ┆ Soma spatial   ┆ Queried from  ┆ ["soma_voxel_ ┆ id            │
│ ial            ┆ _spatial       ┆ features for   ┆ CAVE nucleus  ┆ x", "soma_vox ┆               │
│                ┆                ┆ V1DD…          ┆ tabl…         ┆ el_y…         ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

shape: (1, 4)
┌─────────────────┬───────────────────────────┬────────┬──────────────────────────┐
│ clusterset_id   ┆ run                       ┆ root   ┆ clusters                 │
│ ---             ┆ ---                       ┆ ---    ┆ ---                      │
│ str             ┆ str                       ┆ str    ┆ list[str]                │
╞═════════════════╪═══════════════════════════╪════════╪══════════════════════════╡
│ v1dd_cell_types ┆ v1dd_cell_type_annotation ┆ neuron ┆ ["neuron", "E", … "STC"] │
└─────────────────┴───────────────────────────┴────────┴──────────────────────────┘

## Read all related features and cluster memberships

In [8]:
proofread_axons = reader.read_dataset(AXON_DATASET)
proofread_dendrites = reader.read_dataset(DENDRITE_DATASET)

print("proofread axons:", proofread_axons.shape)
display(proofread_axons.head())

print("proofread dendrites:", proofread_dendrites.shape)
display(proofread_dendrites.head())

proofread axons: (1164, 22)

shape: (5, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ dataitem_ ┆ nucleus_v ┆ nucleus_a ┆ nuclear_a ┆ … ┆ soma_volu ┆ v1dd_cell ┆ v1dd_cell ┆ v1dd_cel │
│ id        ┆ olume_um  ┆ rea_um    ┆ rea_to_vo ┆   ┆ me        ┆ _types_le ┆ _types_le ┆ l_types_ │
│ ---       ┆ ---       ┆ ---       ┆ lume_rati ┆   ┆ ---       ┆ vel_0     ┆ vel_1     ┆ level_2  │
│ str       ┆ f64       ┆ f64       ┆ o         ┆   ┆ f32       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆           ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 864691132 ┆ 224.53995 ┆ 228.43419 ┆ 1.278639  ┆ … ┆ 224.68321 ┆ neuron    ┆ E         ┆ L4-IT    │
│ 534275418 ┆ 2         ┆ 4         ┆           ┆   ┆ 2         ┆           ┆           ┆          │
│ 864691132 ┆ 236.50665 ┆ 246.50925 ┆ 1.332867  ┆ … ┆ 236.63990 ┆ neuron    ┆ E         ┆ L4-IT    │
│ 534315610 ┆ 5         ┆ 4         ┆           ┆   ┆ 8         ┆           ┆           ┆          │
│ 864691132 ┆ 300.20032 ┆ 264.67053 ┆ 1.220714  ┆ … ┆ 300.36608 ┆ neuron    ┆ E         ┆ L6-CT    │
│ 535664474 ┆           ┆ 7         ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│ 864691132 ┆ 278.67367 ┆ 330.24334 ┆ 1.600612  ┆ … ┆ 278.90966 ┆ neuron    ┆ I         ┆ DTC      │
│ 536286810 ┆           ┆ 9         ┆           ┆   ┆ 8         ┆           ┆           ┆          │
│ 864691132 ┆ null      ┆ null      ┆ null      ┆ … ┆ 273.80877 ┆ neuron    ┆ I         ┆ DTC      │
│ 536904794 ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

proofread dendrites: (63986, 22)

shape: (5, 22)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ dataitem_ ┆ nucleus_v ┆ nucleus_a ┆ nuclear_a ┆ … ┆ soma_volu ┆ v1dd_cell ┆ v1dd_cell ┆ v1dd_cel │
│ id        ┆ olume_um  ┆ rea_um    ┆ rea_to_vo ┆   ┆ me        ┆ _types_le ┆ _types_le ┆ l_types_ │
│ ---       ┆ ---       ┆ ---       ┆ lume_rati ┆   ┆ ---       ┆ vel_0     ┆ vel_1     ┆ level_2  │
│ str       ┆ f64       ┆ f64       ┆ o         ┆   ┆ f32       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆           ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 864691132 ┆ 153.71482 ┆ 262.44489 ┆ 1.891226  ┆ … ┆ 153.82702 ┆ null      ┆ null      ┆ null     │
│ 496108732 ┆ 3         ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 864691132 ┆ 257.46175 ┆ 283.77023 ┆ 1.44991   ┆ … ┆ 257.70013 ┆ null      ┆ null      ┆ null     │
│ 511800666 ┆ 4         ┆ 5         ┆           ┆   ┆ 4         ┆           ┆           ┆          │
│ 864691132 ┆ 258.15273 ┆ 266.50496 ┆ 1.359263  ┆ … ┆ 258.20443 ┆ null      ┆ null      ┆ null     │
│ 525163794 ┆ 4         ┆ 2         ┆           ┆   ┆ 7         ┆           ┆           ┆          │
│ 864691132 ┆ 226.83133 ┆ 231.12681 ┆ 1.284983  ┆ … ┆ 226.99195 ┆ neuron    ┆ E         ┆ L4-IT    │
│ 533275738 ┆ 1         ┆ 1         ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│ 864691132 ┆ 217.52302 ┆ 230.47336 ┆ 1.317649  ┆ … ┆ 217.65455 ┆ neuron    ┆ E         ┆ L4-IT    │
│ 533347418 ┆ 7         ┆ 1         ┆           ┆   ┆ 6         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Select only features or only clusters

In [10]:
axon_features_only = reader.read_dataset(
    AXON_DATASET,
    featuresets="v1dd_soma_features",
    clustersets=[],
)
axon_clusters_only = reader.read_dataset(
    AXON_DATASET,
    featuresets=[],
    clustersets="v1dd_cell_types",
)

display(axon_features_only.head())
display(axon_clusters_only.head())

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ dataitem_ ┆ nucleus_v ┆ nucleus_a ┆ nuclear_a ┆ … ┆ soma_area ┆ soma_to_n ┆ soma_area ┆ soma_syn │
│ id        ┆ olume_um  ┆ rea_um    ┆ rea_to_vo ┆   ┆ _um       ┆ ucleus_ce ┆ _to_volum ┆ apse_den │
│ ---       ┆ ---       ┆ ---       ┆ lume_rati ┆   ┆ ---       ┆ nter_dist ┆ e_ratio   ┆ sity_um  │
│ str       ┆ f64       ┆ f64       ┆ o         ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆           ┆ f64       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 864691132 ┆ 224.53995 ┆ 228.43419 ┆ 1.278639  ┆ … ┆ 612.70478 ┆ 0.957844  ┆ 2.03256   ┆ 0.040803 │
│ 534275418 ┆ 2         ┆ 4         ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 864691132 ┆ 236.50665 ┆ 246.50925 ┆ 1.332867  ┆ … ┆ 691.23953 ┆ 1.293702  ┆ 2.102883  ┆ 0.088247 │
│ 534315610 ┆ 5         ┆ 4         ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│ 864691132 ┆ 300.20032 ┆ 264.67053 ┆ 1.220714  ┆ … ┆ 923.13383 ┆ 0.524689  ┆ 2.300336  ┆ 0.080162 │
│ 535664474 ┆           ┆ 7         ┆           ┆   ┆ 5         ┆           ┆           ┆          │
│ 864691132 ┆ 278.67367 ┆ 330.24334 ┆ 1.600612  ┆ … ┆ 707.65966 ┆ 1.442203  ┆ 1.804908  ┆ 0.240228 │
│ 536286810 ┆           ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 864691132 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 536904794 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (5, 4)
┌────────────────────┬─────────────────────────┬─────────────────────────┬─────────────────────────┐
│ dataitem_id        ┆ v1dd_cell_types_level_0 ┆ v1dd_cell_types_level_1 ┆ v1dd_cell_types_level_2 │
│ ---                ┆ ---                     ┆ ---                     ┆ ---                     │
│ str                ┆ str                     ┆ str                     ┆ str                     │
╞════════════════════╪═════════════════════════╪═════════════════════════╪═════════════════════════╡
│ 864691132534275418 ┆ neuron                  ┆ E                       ┆ L4-IT                   │
│ 864691132534315610 ┆ neuron                  ┆ E                       ┆ L4-IT                   │
│ 864691132535664474 ┆ neuron                  ┆ E                       ┆ L6-CT                   │
│ 864691132536286810 ┆ neuron                  ┆ I                       ┆ DTC                     │
│ 864691132536904794 ┆ neuron                  ┆ I                       ┆ DTC                     │
└────────────────────┴─────────────────────────┴─────────────────────────┴─────────────────────────┘

## Validate the example

In [11]:
feature_columns = {
    "soma_voxel_x",
    "soma_voxel_y",
    "soma_voxel_z",
    "soma_transformed_x",
    "soma_transformed_y",
    "soma_transformed_z",
    "soma_volume",
}
cluster_columns = {
    "v1dd_cell_types_level_0",
    "v1dd_cell_types_level_1",
    "v1dd_cell_types_level_2",
}

assert proofread_axons.height == 1_164
assert proofread_dendrites.height == 63_986
assert feature_columns <= set(proofread_axons.columns)
assert feature_columns <= set(proofread_dendrites.columns)
assert cluster_columns <= set(proofread_axons.columns)
assert cluster_columns <= set(proofread_dendrites.columns)
assert proofread_axons["dataitem_id"].n_unique() == proofread_axons.height
assert proofread_dendrites["dataitem_id"].n_unique() == proofread_dendrites.height
assert proofread_axons.select(
    pl.col("v1dd_cell_types_level_2").is_null().sum()
).item() > 0
assert proofread_dendrites.select(
    pl.col("v1dd_cell_types_level_2").is_null().sum()
).item() > 0

print("DatasetReader V1DD proofread-cohort checks passed.")

DatasetReader V1DD proofread-cohort checks passed.