# Read V1DD datasets with `DatasetReader`

This notebook demonstrates dataset discovery and wide reads for the V1DD release 1196 proofread axon and dendrite cohorts.

In [1]:
from pathlib import Path

import polars as pl

from connects_common_connectivity.io import DatasetReader

In [3]:
DATASET_ROOT = Path("../scratch/v1dd_1196_v2")
AXON_DATASET = "v1dd_1196_proofread_axons"
DENDRITE_DATASET = "v1dd_1196_proofread_dendrites"

reader = DatasetReader(DATASET_ROOT)

## Available datasets

In [4]:
reader.display_dataset_names()

shape: (3, 4)
┌───────────────────────────────┬───────────────────────────────┬────────────┬─────────────────────┐
│ id                            ┆ name                          ┆ project_id ┆ modality            │
│ ---                           ┆ ---                           ┆ ---        ┆ ---                 │
│ str                           ┆ str                           ┆ str        ┆ str                 │
╞═══════════════════════════════╪═══════════════════════════════╪════════════╪═════════════════════╡
│ v1dd_1196_em                  ┆ V1DD release 1196 — EM somas  ┆ v1dd       ┆ ELECTRON_MICROSCOPY │
│ v1dd_1196_proofread_axons     ┆ V1DD release 1196 — proofread ┆ v1dd       ┆ ELECTRON_MICROSCOPY │
│                               ┆ …                             ┆            ┆                     │
│ v1dd_1196_proofread_dendrites ┆ V1DD release 1196 — proofread ┆ v1dd       ┆ ELECTRON_MICROSCOPY │
│                               ┆ …                             ┆            ┆                     │
└───────────────────────────────┴───────────────────────────────┴────────────┴─────────────────────┘

## Related feature sets and cluster sets

In [4]:
for dataset_name in (AXON_DATASET, DENDRITE_DATASET):
    print(dataset_name)
    display(reader.display_featuresets(dataset_name))
    display(reader.display_clustersets(dataset_name))

v1dd_1196_proofread_axons

shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ feature_set_id ┆ matrix_id      ┆ description    ┆ extraction_me ┆ feature_defin ┆ cell_index_co │
│ ---            ┆ ---            ┆ ---            ┆ thod          ┆ ition_ids     ┆ lumn          │
│ str            ┆ str            ┆ str            ┆ ---           ┆ ---           ┆ ---           │
│                ┆                ┆                ┆ str           ┆ list[str]     ┆ str           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ v1dd_soma_spat ┆ v1dd_v1dd_soma ┆ Soma spatial   ┆ Queried from  ┆ ["soma_voxel_ ┆ id            │
│ ial            ┆ _spatial       ┆ features for   ┆ CAVE nucleus  ┆ x", "soma_vox ┆               │
│                ┆                ┆ V1DD…          ┆ tabl…         ┆ el_y…         ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

shape: (1, 4)
┌─────────────────┬───────────────────────────┬────────┬──────────────────────────┐
│ clusterset_id   ┆ run                       ┆ root   ┆ clusters                 │
│ ---             ┆ ---                       ┆ ---    ┆ ---                      │
│ str             ┆ str                       ┆ str    ┆ list[str]                │
╞═════════════════╪═══════════════════════════╪════════╪══════════════════════════╡
│ v1dd_cell_types ┆ v1dd_cell_type_annotation ┆ neuron ┆ ["neuron", "E", … "STC"] │
└─────────────────┴───────────────────────────┴────────┴──────────────────────────┘

v1dd_1196_proofread_dendrites

shape: (1, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ feature_set_id ┆ matrix_id      ┆ description    ┆ extraction_me ┆ feature_defin ┆ cell_index_co │
│ ---            ┆ ---            ┆ ---            ┆ thod          ┆ ition_ids     ┆ lumn          │
│ str            ┆ str            ┆ str            ┆ ---           ┆ ---           ┆ ---           │
│                ┆                ┆                ┆ str           ┆ list[str]     ┆ str           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ v1dd_soma_spat ┆ v1dd_v1dd_soma ┆ Soma spatial   ┆ Queried from  ┆ ["soma_voxel_ ┆ id            │
│ ial            ┆ _spatial       ┆ features for   ┆ CAVE nucleus  ┆ x", "soma_vox ┆               │
│                ┆                ┆ V1DD…          ┆ tabl…         ┆ el_y…         ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

shape: (1, 4)
┌─────────────────┬───────────────────────────┬────────┬──────────────────────────┐
│ clusterset_id   ┆ run                       ┆ root   ┆ clusters                 │
│ ---             ┆ ---                       ┆ ---    ┆ ---                      │
│ str             ┆ str                       ┆ str    ┆ list[str]                │
╞═════════════════╪═══════════════════════════╪════════╪══════════════════════════╡
│ v1dd_cell_types ┆ v1dd_cell_type_annotation ┆ neuron ┆ ["neuron", "E", … "STC"] │
└─────────────────┴───────────────────────────┴────────┴──────────────────────────┘

## Read all related features and cluster memberships

In [5]:
proofread_axons = reader.read_dataset(AXON_DATASET)
proofread_dendrites = reader.read_dataset(DENDRITE_DATASET)

print("proofread axons:", proofread_axons.shape)
display(proofread_axons.head())

print("proofread dendrites:", proofread_dendrites.shape)
display(proofread_dendrites.head())

proofread axons: (1164, 11)

shape: (5, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ dataitem_ ┆ soma_voxe ┆ soma_voxe ┆ soma_voxe ┆ … ┆ soma_volu ┆ v1dd_cell ┆ v1dd_cell ┆ v1dd_cel │
│ id        ┆ l_x       ┆ l_y       ┆ l_z       ┆   ┆ me        ┆ _types_le ┆ _types_le ┆ l_types_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ vel_0     ┆ vel_1     ┆ level_2  │
│ str       ┆ f32       ┆ f32       ┆ f32       ┆   ┆ f32       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 864691132 ┆ 739373.0  ┆ 633371.0  ┆ 323640.0  ┆ … ┆ 224.68321 ┆ neuron    ┆ E         ┆ L4-IT    │
│ 534275418 ┆           ┆           ┆           ┆   ┆ 2         ┆           ┆           ┆          │
│ 864691132 ┆ 823103.0  ┆ 635932.0  ┆ 272970.0  ┆ … ┆ 236.63990 ┆ neuron    ┆ E         ┆ L4-IT    │
│ 534315610 ┆           ┆           ┆           ┆   ┆ 8         ┆           ┆           ┆          │
│ 864691132 ┆ 972173.0  ┆ 1.006782e ┆ 429480.0  ┆ … ┆ 300.36608 ┆ neuron    ┆ E         ┆ L6-CT    │
│ 535664474 ┆           ┆ 6         ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│ 864691132 ┆ 860041.0  ┆ 818137.0  ┆ 270495.0  ┆ … ┆ 278.90966 ┆ neuron    ┆ I         ┆ DTC      │
│ 536286810 ┆           ┆           ┆           ┆   ┆ 8         ┆           ┆           ┆          │
│ 864691132 ┆ 940822.0  ┆ 738674.0  ┆ 146565.0  ┆ … ┆ 273.80877 ┆ neuron    ┆ I         ┆ DTC      │
│ 536904794 ┆           ┆           ┆           ┆   ┆ 7         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

proofread dendrites: (63986, 11)

shape: (5, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ dataitem_ ┆ soma_voxe ┆ soma_voxe ┆ soma_voxe ┆ … ┆ soma_volu ┆ v1dd_cell ┆ v1dd_cell ┆ v1dd_cel │
│ id        ┆ l_x       ┆ l_y       ┆ l_z       ┆   ┆ me        ┆ _types_le ┆ _types_le ┆ l_types_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ vel_0     ┆ vel_1     ┆ level_2  │
│ str       ┆ f32       ┆ f32       ┆ f32       ┆   ┆ f32       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 864691132 ┆ 1.65513e6 ┆ 605358.0  ┆ 776205.0  ┆ … ┆ 153.82702 ┆ null      ┆ null      ┆ null     │
│ 496108732 ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 864691132 ┆ 1.227399e ┆ 659134.0  ┆ 270000.0  ┆ … ┆ 257.70013 ┆ null      ┆ null      ┆ null     │
│ 511800666 ┆ 6         ┆           ┆           ┆   ┆ 4         ┆           ┆           ┆          │
│ 864691132 ┆ 1.546956e ┆ 533345.0  ┆ 771210.0  ┆ … ┆ 258.20443 ┆ null      ┆ null      ┆ null     │
│ 525163794 ┆ 6         ┆           ┆           ┆   ┆ 7         ┆           ┆           ┆          │
│ 864691132 ┆ 641054.0  ┆ 609626.0  ┆ 372420.0  ┆ … ┆ 226.99195 ┆ neuron    ┆ E         ┆ L4-IT    │
│ 533275738 ┆           ┆           ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│ 864691132 ┆ 805488.0  ┆ 633759.0  ┆ 299205.0  ┆ … ┆ 217.65455 ┆ neuron    ┆ E         ┆ L4-IT    │
│ 533347418 ┆           ┆           ┆           ┆   ┆ 6         ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Select only features or only clusters

In [6]:
axon_features_only = reader.read_dataset(
    AXON_DATASET,
    featuresets="v1dd_soma_spatial",
    clustersets=[],
)
axon_clusters_only = reader.read_dataset(
    AXON_DATASET,
    featuresets=[],
    clustersets="v1dd_cell_types",
)

display(axon_features_only.head())
display(axon_clusters_only.head())

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ dataitem_i ┆ soma_voxel ┆ soma_voxel ┆ soma_voxe ┆ soma_tran ┆ soma_tran ┆ soma_tran ┆ soma_volu │
│ d          ┆ _x         ┆ _y         ┆ l_z       ┆ sformed_x ┆ sformed_y ┆ sformed_z ┆ me        │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ f32        ┆ f32        ┆ f32       ┆ f32       ┆ f32       ┆ f32       ┆ f32       │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 8646911325 ┆ 739373.0   ┆ 633371.0   ┆ 323640.0  ┆ -149.8431 ┆ 313.61944 ┆ 40.652767 ┆ 224.68321 │
│ 34275418   ┆            ┆            ┆           ┆ 55        ┆ 6         ┆           ┆ 2         │
│ 8646911325 ┆ 823103.0   ┆ 635932.0   ┆ 272970.0  ┆ -64.43122 ┆ 301.97753 ┆ -9.080418 ┆ 236.63990 │
│ 34315610   ┆            ┆            ┆           ┆ 1         ┆ 9         ┆           ┆ 8         │
│ 8646911325 ┆ 972173.0   ┆ 1.006782e6 ┆ 429480.0  ┆ -56.72760 ┆ 731.34851 ┆ -1.565523 ┆ 300.36608 │
│ 35664474   ┆            ┆            ┆           ┆ 4         ┆ 1         ┆           ┆ 9         │
│ 8646911325 ┆ 860041.0   ┆ 818137.0   ┆ 270495.0  ┆ -68.29425 ┆ 481.95327 ┆ -64.04815 ┆ 278.90966 │
│ 36286810   ┆            ┆            ┆           ┆ 8         ┆ 8         ┆ 7         ┆ 8         │
│ 8646911325 ┆ 940822.0   ┆ 738674.0   ┆ 146565.0  ┆ 41.834404 ┆ 367.66186 ┆ -158.0780 ┆ 273.80877 │
│ 36904794   ┆            ┆            ┆           ┆           ┆ 5         ┆ 94        ┆ 7         │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

shape: (5, 4)
┌────────────────────┬─────────────────────────┬─────────────────────────┬─────────────────────────┐
│ dataitem_id        ┆ v1dd_cell_types_level_0 ┆ v1dd_cell_types_level_1 ┆ v1dd_cell_types_level_2 │
│ ---                ┆ ---                     ┆ ---                     ┆ ---                     │
│ str                ┆ str                     ┆ str                     ┆ str                     │
╞════════════════════╪═════════════════════════╪═════════════════════════╪═════════════════════════╡
│ 864691132534275418 ┆ neuron                  ┆ E                       ┆ L4-IT                   │
│ 864691132534315610 ┆ neuron                  ┆ E                       ┆ L4-IT                   │
│ 864691132535664474 ┆ neuron                  ┆ E                       ┆ L6-CT                   │
│ 864691132536286810 ┆ neuron                  ┆ I                       ┆ DTC                     │
│ 864691132536904794 ┆ neuron                  ┆ I                       ┆ DTC                     │
└────────────────────┴─────────────────────────┴─────────────────────────┴─────────────────────────┘

## Validate the example

In [7]:
feature_columns = {
    "soma_voxel_x",
    "soma_voxel_y",
    "soma_voxel_z",
    "soma_transformed_x",
    "soma_transformed_y",
    "soma_transformed_z",
    "soma_volume",
}
cluster_columns = {
    "v1dd_cell_types_level_0",
    "v1dd_cell_types_level_1",
    "v1dd_cell_types_level_2",
}

assert proofread_axons.height == 1_164
assert proofread_dendrites.height == 63_986
assert feature_columns <= set(proofread_axons.columns)
assert feature_columns <= set(proofread_dendrites.columns)
assert cluster_columns <= set(proofread_axons.columns)
assert cluster_columns <= set(proofread_dendrites.columns)
assert proofread_axons["dataitem_id"].n_unique() == proofread_axons.height
assert proofread_dendrites["dataitem_id"].n_unique() == proofread_dendrites.height
assert proofread_axons.select(
    pl.col("v1dd_cell_types_level_2").is_null().sum()
).item() > 0
assert proofread_dendrites.select(
    pl.col("v1dd_cell_types_level_2").is_null().sum()
).item() > 0

print("DatasetReader V1DD proofread-cohort checks passed.")

DatasetReader V1DD proofread-cohort checks passed.