# Read V1DD release-ingest data

Read the V1DD datasets plus the dedicated spatial-location, embedding, and connectome tables introduced by the release-ingest schema.

In [13]:
import polars as pl
from IPython.display import display

from connects_common_connectivity.config import get_settings
from connects_common_connectivity.io import (
    DatasetReader,
    read_cell_cell_connectivity,
    read_embedding_locations,
    read_embedding_spaces,
    read_reference_spaces,
    read_spatial_locations,
)
from connects_common_connectivity.models import LocationType

In [3]:
DATASET_ROOT = get_settings().output_root
PROJECT_ID = "v1dd_1196"
AXON_DATASET = "v1dd_1196_proofread_axons"
DENDRITE_DATASET = "v1dd_1196_proofread_dendrites"
HIERARCHY_ID = "EM_csm_cell_types"
CONNECTOME_ID = "v1dd_1196_em_proofread_axon_to_dendrite"
SYNAPSE_TABLE_ID = "v1dd_1196_synapses"
QC_EMBEDDING_ID = "v1dd_r84_qc_nonnull_umap"
AD_REF_EMBEDDING_ID = "v1dd_r84_ad_ref_umap"

reader = DatasetReader(DATASET_ROOT)

## Available datasets

In [14]:
reader.display_dataset_names()

shape: (3, 4)
┌───────────────────────────────┬───────────────────────────────┬────────────┬─────────────────────┐
│ id                            ┆ name                          ┆ project_id ┆ modality            │
│ ---                           ┆ ---                           ┆ ---        ┆ ---                 │
│ str                           ┆ str                           ┆ str        ┆ str                 │
╞═══════════════════════════════╪═══════════════════════════════╪════════════╪═════════════════════╡
│ v1dd_1196_all                 ┆ V1DD release 1196 — EM somas  ┆ v1dd_1196  ┆ ELECTRON_MICROSCOPY │
│ v1dd_1196_proofread_axons     ┆ V1DD release 1196 — proofread ┆ v1dd_1196  ┆ ELECTRON_MICROSCOPY │
│                               ┆ …                             ┆            ┆                     │
│ v1dd_1196_proofread_dendrites ┆ V1DD release 1196 — proofread ┆ v1dd_1196  ┆ ELECTRON_MICROSCOPY │
│                               ┆ …                             ┆            ┆                     │
└───────────────────────────────┴───────────────────────────────┴────────────┴─────────────────────┘

## Related feature sets and cluster sets

In [5]:
for dataset_name in (AXON_DATASET, DENDRITE_DATASET):
    print(dataset_name)
    display(reader.display_featuresets(dataset_name))
    display(reader.display_clustersets(dataset_name))
    print('\n\n\n\n')

v1dd_1196_proofread_axons

shape: (2, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ feature_set_id ┆ matrix_id      ┆ description    ┆ extraction_me ┆ feature_defin ┆ cell_index_co │
│ ---            ┆ ---            ┆ ---            ┆ thod          ┆ ition_ids     ┆ lumn          │
│ str            ┆ str            ┆ str            ┆ ---           ┆ ---           ┆ ---           │
│                ┆                ┆                ┆ str           ┆ list[str]     ┆ str           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ v1dd_soma_feat ┆ v1dd_1196_v1dd ┆ V1DD soma      ┆ Loaded from   ┆ ["nucleus_vol ┆ id            │
│ ures           ┆ _soma_features ┆ morphology and ┆ v1dd_v1196    ┆ ume_um",      ┆               │
│                ┆                ┆ nucle…         ┆ soma_fe…      ┆ "nucleus…     ┆               │
│ v1dd_soma_volu ┆ v1dd_1196_v1dd ┆ V1DD release   ┆ Queried from  ┆ ["soma_volume ┆ id            │
│ me             ┆ _soma_volume   ┆ 1196 soma      ┆ the CAVE      ┆ "]            ┆               │
│                ┆                ┆ nucleus…       ┆ nucleus …     ┆               ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

shape: (1, 4)
┌───────────────────┬───────────────────────────────┬────────┬─────────────────────────────────┐
│ clusterset_id     ┆ run                           ┆ root   ┆ clusters                        │
│ ---               ┆ ---                           ┆ ---    ┆ ---                             │
│ str               ┆ str                           ┆ str    ┆ list[str]                       │
╞═══════════════════╪═══════════════════════════════╪════════╪═════════════════════════════════╡
│ EM_csm_cell_types ┆ v1dd_cell_type_annotation_r84 ┆ neuron ┆ ["neuron", "exc", … "Neuroglia… │
└───────────────────┴───────────────────────────────┴────────┴─────────────────────────────────┘

v1dd_1196_proofread_dendrites

shape: (2, 6)
┌────────────────┬────────────────┬────────────────┬───────────────┬───────────────┬───────────────┐
│ feature_set_id ┆ matrix_id      ┆ description    ┆ extraction_me ┆ feature_defin ┆ cell_index_co │
│ ---            ┆ ---            ┆ ---            ┆ thod          ┆ ition_ids     ┆ lumn          │
│ str            ┆ str            ┆ str            ┆ ---           ┆ ---           ┆ ---           │
│                ┆                ┆                ┆ str           ┆ list[str]     ┆ str           │
╞════════════════╪════════════════╪════════════════╪═══════════════╪═══════════════╪═══════════════╡
│ v1dd_soma_feat ┆ v1dd_1196_v1dd ┆ V1DD soma      ┆ Loaded from   ┆ ["nucleus_vol ┆ id            │
│ ures           ┆ _soma_features ┆ morphology and ┆ v1dd_v1196    ┆ ume_um",      ┆               │
│                ┆                ┆ nucle…         ┆ soma_fe…      ┆ "nucleus…     ┆               │
│ v1dd_soma_volu ┆ v1dd_1196_v1dd ┆ V1DD release   ┆ Queried from  ┆ ["soma_volume ┆ id            │
│ me             ┆ _soma_volume   ┆ 1196 soma      ┆ the CAVE      ┆ "]            ┆               │
│                ┆                ┆ nucleus…       ┆ nucleus …     ┆               ┆               │
└────────────────┴────────────────┴────────────────┴───────────────┴───────────────┴───────────────┘

shape: (1, 4)
┌───────────────────┬───────────────────────────────┬────────┬─────────────────────────────────┐
│ clusterset_id     ┆ run                           ┆ root   ┆ clusters                        │
│ ---               ┆ ---                           ┆ ---    ┆ ---                             │
│ str               ┆ str                           ┆ str    ┆ list[str]                       │
╞═══════════════════╪═══════════════════════════════╪════════╪═════════════════════════════════╡
│ EM_csm_cell_types ┆ v1dd_cell_type_annotation_r84 ┆ neuron ┆ ["neuron", "exc", … "Neuroglia… │
└───────────────────┴───────────────────────────────┴────────┴─────────────────────────────────┘

## Read dataset features and r84 cluster memberships

In [6]:
proofread_axons = reader.read_dataset(AXON_DATASET)
proofread_dendrites = reader.read_dataset(DENDRITE_DATASET)

print("proofread axons:", proofread_axons.shape)
display(proofread_axons.head())

print("proofread dendrites:", proofread_dendrites.shape)
display(proofread_dendrites.head())

proofread axons: (1164, 17)

shape: (5, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ dataitem_ ┆ nucleus_v ┆ nucleus_a ┆ nuclear_a ┆ … ┆ EM_csm_ce ┆ EM_csm_ce ┆ EM_csm_ce ┆ EM_csm_c │
│ id        ┆ olume_um  ┆ rea_um    ┆ rea_to_vo ┆   ┆ ll_types_ ┆ ll_types_ ┆ ll_types_ ┆ ell_type │
│ ---       ┆ ---       ┆ ---       ┆ lume_rati ┆   ┆ level_0   ┆ level_1   ┆ level_2   ┆ s_level_ │
│ str       ┆ f64       ┆ f64       ┆ o         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 3        │
│           ┆           ┆           ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 864691132 ┆ 224.53995 ┆ 228.43419 ┆ 1.278639  ┆ … ┆ neuron    ┆ exc       ┆ L4        ┆ L4:L4-b  │
│ 534275418 ┆ 2         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 864691132 ┆ 236.50665 ┆ 246.50925 ┆ 1.332867  ┆ … ┆ neuron    ┆ exc       ┆ L4        ┆ L4:L4-d  │
│ 534315610 ┆ 5         ┆ 4         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 864691132 ┆ 300.20032 ┆ 264.67053 ┆ 1.220714  ┆ … ┆ neuron    ┆ exc       ┆ L6CT      ┆ L6CT:L6C │
│ 535664474 ┆           ┆ 7         ┆           ┆   ┆           ┆           ┆           ┆ T-a      │
│ 864691132 ┆ 278.67367 ┆ 330.24334 ┆ 1.600612  ┆ … ┆ neuron    ┆ inh       ┆ Martinott ┆ Martinot │
│ 536286810 ┆           ┆ 9         ┆           ┆   ┆           ┆           ┆ iFamily   ┆ tiFamily │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :Martino │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ttiFam…  │
│ 864691132 ┆ null      ┆ null      ┆ null      ┆ … ┆ neuron    ┆ inh       ┆ Martinott ┆ Martinot │
│ 536904794 ┆           ┆           ┆           ┆   ┆           ┆           ┆ iFamily   ┆ tiFamily │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ :Martino │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ttiFam…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

proofread dendrites: (63986, 17)

shape: (5, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ dataitem_ ┆ nucleus_v ┆ nucleus_a ┆ nuclear_a ┆ … ┆ EM_csm_ce ┆ EM_csm_ce ┆ EM_csm_ce ┆ EM_csm_c │
│ id        ┆ olume_um  ┆ rea_um    ┆ rea_to_vo ┆   ┆ ll_types_ ┆ ll_types_ ┆ ll_types_ ┆ ell_type │
│ ---       ┆ ---       ┆ ---       ┆ lume_rati ┆   ┆ level_0   ┆ level_1   ┆ level_2   ┆ s_level_ │
│ str       ┆ f64       ┆ f64       ┆ o         ┆   ┆ ---       ┆ ---       ┆ ---       ┆ 3        │
│           ┆           ┆           ┆ ---       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 864691132 ┆ 153.71482 ┆ 262.44489 ┆ 1.891226  ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 496108732 ┆ 3         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 864691132 ┆ 257.46175 ┆ 283.77023 ┆ 1.44991   ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 511800666 ┆ 4         ┆ 5         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 864691132 ┆ 258.15273 ┆ 266.50496 ┆ 1.359263  ┆ … ┆ neuron    ┆ exc       ┆ L4        ┆ L4:L4-b  │
│ 525163794 ┆ 4         ┆ 2         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 864691132 ┆ 226.83133 ┆ 231.12681 ┆ 1.284983  ┆ … ┆ neuron    ┆ exc       ┆ L4        ┆ L4:L4-b  │
│ 533275738 ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 864691132 ┆ 217.52302 ┆ 230.47336 ┆ 1.317649  ┆ … ┆ neuron    ┆ exc       ┆ L4        ┆ L4:L4-b  │
│ 533347418 ┆ 7         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Select only features or only clusters

In [7]:
axon_features_only = reader.read_dataset(
    AXON_DATASET,
    featuresets="v1dd_soma_features",
    clustersets=[],
)
axon_clusters_only = reader.read_dataset(
    AXON_DATASET,
    featuresets=[],
    clustersets=HIERARCHY_ID,
)

display(axon_features_only.head())
display(axon_clusters_only.head())

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ dataitem_ ┆ nucleus_v ┆ nucleus_a ┆ nuclear_a ┆ … ┆ soma_area ┆ soma_to_n ┆ soma_area ┆ soma_syn │
│ id        ┆ olume_um  ┆ rea_um    ┆ rea_to_vo ┆   ┆ _um       ┆ ucleus_ce ┆ _to_volum ┆ apse_den │
│ ---       ┆ ---       ┆ ---       ┆ lume_rati ┆   ┆ ---       ┆ nter_dist ┆ e_ratio   ┆ sity_um  │
│ str       ┆ f64       ┆ f64       ┆ o         ┆   ┆ f64       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆ ---       ┆   ┆           ┆ f64       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆ f64       ┆   ┆           ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 864691132 ┆ 224.53995 ┆ 228.43419 ┆ 1.278639  ┆ … ┆ 612.70478 ┆ 0.957844  ┆ 2.03256   ┆ 0.040803 │
│ 534275418 ┆ 2         ┆ 4         ┆           ┆   ┆ 6         ┆           ┆           ┆          │
│ 864691132 ┆ 236.50665 ┆ 246.50925 ┆ 1.332867  ┆ … ┆ 691.23953 ┆ 1.293702  ┆ 2.102883  ┆ 0.088247 │
│ 534315610 ┆ 5         ┆ 4         ┆           ┆   ┆ 9         ┆           ┆           ┆          │
│ 864691132 ┆ 300.20032 ┆ 264.67053 ┆ 1.220714  ┆ … ┆ 923.13383 ┆ 0.524689  ┆ 2.300336  ┆ 0.080162 │
│ 535664474 ┆           ┆ 7         ┆           ┆   ┆ 5         ┆           ┆           ┆          │
│ 864691132 ┆ 278.67367 ┆ 330.24334 ┆ 1.600612  ┆ … ┆ 707.65966 ┆ 1.442203  ┆ 1.804908  ┆ 0.240228 │
│ 536286810 ┆           ┆ 9         ┆           ┆   ┆           ┆           ┆           ┆          │
│ 864691132 ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 536904794 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (5, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ dataitem_id       ┆ EM_csm_cell_types ┆ EM_csm_cell_types ┆ EM_csm_cell_types ┆ EM_csm_cell_type │
│ ---               ┆ _level_0          ┆ _level_1          ┆ _level_2          ┆ s_level_3        │
│ str               ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│                   ┆ str               ┆ str               ┆ str               ┆ str              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ 86469113253427541 ┆ neuron            ┆ exc               ┆ L4                ┆ L4:L4-b          │
│ 8                 ┆                   ┆                   ┆                   ┆                  │
│ 86469113253431561 ┆ neuron            ┆ exc               ┆ L4                ┆ L4:L4-d          │
│ 0                 ┆                   ┆                   ┆                   ┆                  │
│ 86469113253566447 ┆ neuron            ┆ exc               ┆ L6CT              ┆ L6CT:L6CT-a      │
│ 4                 ┆                   ┆                   ┆                   ┆                  │
│ 86469113253628681 ┆ neuron            ┆ inh               ┆ MartinottiFamily  ┆ MartinottiFamily │
│ 0                 ┆                   ┆                   ┆                   ┆ :MartinottiFam…  │
│ 86469113253690479 ┆ neuron            ┆ inh               ┆ MartinottiFamily  ┆ MartinottiFamily │
│ 4                 ┆                   ┆                   ┆                   ┆ :MartinottiFam…  │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

## Validate dataset-centric reads

In [8]:
cluster_columns = {
    f"{HIERARCHY_ID}_level_1",
    f"{HIERARCHY_ID}_level_2",
    f"{HIERARCHY_ID}_level_3",
}

assert proofread_axons.height > 0
assert proofread_dendrites.height > 0
assert proofread_axons["dataitem_id"].n_unique() == proofread_axons.height
assert proofread_dendrites["dataitem_id"].n_unique() == proofread_dendrites.height
assert cluster_columns <= set(proofread_axons.columns)
assert cluster_columns <= set(proofread_dendrites.columns)
assert proofread_axons.select(
    pl.col(f"{HIERARCHY_ID}_level_2").is_not_null().sum()
).item() > 0
assert proofread_dendrites.select(
    pl.col(f"{HIERARCHY_ID}_level_2").is_not_null().sum()
).item() > 0

print("DatasetReader V1DD proofread-cohort checks passed.")

DatasetReader V1DD proofread-cohort checks passed.

In [11]:
reference_spaces = read_reference_spaces(
    project_id=PROJECT_ID, output_root=DATASET_ROOT
)
soma_locations = read_spatial_locations(
    PROJECT_ID,
    location_types=LocationType.SOMA,
    output_root=DATASET_ROOT,
)
embedding_spaces = read_embedding_spaces(
    PROJECT_ID, output_root=DATASET_ROOT
)
qc_embedding = read_embedding_locations(
    PROJECT_ID,
    embedding_space_ids=QC_EMBEDDING_ID,
    output_root=DATASET_ROOT,
)
ad_ref_embedding = read_embedding_locations(
    PROJECT_ID,
    embedding_space_ids=AD_REF_EMBEDDING_ID,
    output_root=DATASET_ROOT,
)
connectivity = read_cell_cell_connectivity(
    PROJECT_ID,
    CONNECTOME_ID,
    synapse_table_id=SYNAPSE_TABLE_ID,
    output_root=DATASET_ROOT,
)

assert {"v1dd_cave_nm", "v1dd_streamline_nm"} <= set(
    reference_spaces["id"].to_list()
)
assert soma_locations.select(
    "dataitem_id", "reference_space", "location_type"
).unique().height == soma_locations.height
assert {QC_EMBEDDING_ID, AD_REF_EMBEDDING_ID} <= set(
    embedding_spaces["id"].to_list()
)
assert qc_embedding["dataitem_id"].n_unique() == qc_embedding.height
assert ad_ref_embedding["dataitem_id"].n_unique() == ad_ref_embedding.height
assert connectivity["id"].n_unique() == connectivity.height
assert connectivity["connectome_id"].unique().to_list() == [CONNECTOME_ID]

display(reference_spaces)
display(soma_locations.head())
display(embedding_spaces)
display(qc_embedding.head())
display(ad_ref_embedding.head())
display(connectivity.head())

shape: (2, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ project_i ┆ id        ┆ name      ┆ descripti ┆ … ┆ voxel_siz ┆ voxel_siz ┆ default_2 ┆ anatomic │
│ d         ┆ ---       ┆ ---       ┆ on        ┆   ┆ e         ┆ e_unit    ┆ d_view    ┆ al_orien │
│ ---       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ tation   │
│ str       ┆           ┆           ┆ str       ┆   ┆ list[f64] ┆ str       ┆ struct[2] ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ struct[7 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ v1dd_1196 ┆ v1dd_cave ┆ V1DD CAVE ┆ Soma      ┆ … ┆ null      ┆ null      ┆ {"PLUS_X" ┆ {null,nu │
│           ┆ _nm       ┆ nanometer ┆ nucleus   ┆   ┆           ┆           ┆ ,"MINUS_Y ┆ ll,null, │
│           ┆           ┆ coordinat ┆ positions ┆   ┆           ┆           ┆ "}        ┆ null,nul │
│           ┆           ┆ e…        ┆ returne…  ┆   ┆           ┆           ┆           ┆ l,null…  │
│ v1dd_1196 ┆ v1dd_stre ┆ V1DD stre ┆ Soma      ┆ … ┆ null      ┆ null      ┆ {"PLUS_X" ┆ {null,nu │
│           ┆ amline_nm ┆ amline-tr ┆ nucleus   ┆   ┆           ┆           ┆ ,"MINUS_Y ┆ ll,null, │
│           ┆           ┆ ansformed ┆ positions ┆   ┆           ┆           ┆ "}        ┆ null,nul │
│           ┆           ┆ na…       ┆ transfo…  ┆   ┆           ┆           ┆           ┆ l,null…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (5, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ project_id ┆ dataitem_i ┆ reference_ ┆ location_ ┆ descripti ┆ x         ┆ y         ┆ z         │
│ ---        ┆ d          ┆ space      ┆ type      ┆ on        ┆ ---       ┆ ---       ┆ ---       │
│ str        ┆ ---        ┆ ---        ┆ ---       ┆ ---       ┆ f64       ┆ f64       ┆ f64       │
│            ┆ str        ┆ str        ┆ str       ┆ str       ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ v1dd_1196  ┆ 8646911326 ┆ v1dd_cave_ ┆ SOMA      ┆ Soma      ┆ 624680.0  ┆ 531094.0  ┆ 283770.0  │
│            ┆ 54552792   ┆ nm         ┆           ┆ nucleus   ┆           ┆           ┆           │
│            ┆            ┆            ┆           ┆ position  ┆           ┆           ┆           │
│            ┆            ┆            ┆           ┆ from CAV… ┆           ┆           ┆           │
│ v1dd_1196  ┆ 8646911326 ┆ v1dd_strea ┆ SOMA      ┆ Streamlin ┆ -248.9569 ┆ 222.05490 ┆ 16.022035 │
│            ┆ 54552792   ┆ mline_nm   ┆           ┆ e-transfo ┆ 09        ┆ 7         ┆           │
│            ┆            ┆            ┆           ┆ rmed soma ┆           ┆           ┆           │
│            ┆            ┆            ┆           ┆ nu…       ┆           ┆           ┆           │
│ v1dd_1196  ┆ 8646911327 ┆ v1dd_cave_ ┆ SOMA      ┆ Soma      ┆ 894573.0  ┆ 478559.0  ┆ 163530.0  │
│            ┆ 73514104   ┆ nm         ┆           ┆ nucleus   ┆           ┆           ┆           │
│            ┆            ┆            ┆           ┆ position  ┆           ┆           ┆           │
│            ┆            ┆            ┆           ┆ from CAV… ┆           ┆           ┆           │
│ v1dd_1196  ┆ 8646911327 ┆ v1dd_strea ┆ SOMA      ┆ Streamlin ┆ 30.864259 ┆ 135.36798 ┆ -105.0977 │
│            ┆ 73514104   ┆ mline_nm   ┆           ┆ e-transfo ┆           ┆ 4         ┆ 54        │
│            ┆            ┆            ┆           ┆ rmed soma ┆           ┆           ┆           │
│            ┆            ┆            ┆           ┆ nu…       ┆           ┆           ┆           │
│ v1dd_1196  ┆ 8646911327 ┆ v1dd_cave_ ┆ SOMA      ┆ Soma      ┆ 1.729859e ┆ 674111.0  ┆ 781200.0  │
│            ┆ 74106773   ┆ nm         ┆           ┆ nucleus   ┆ 6         ┆           ┆           │
│            ┆            ┆            ┆           ┆ position  ┆           ┆           ┆           │
│            ┆            ┆            ┆           ┆ from CAV… ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

shape: (2, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ project_i ┆ id        ┆ name      ┆ descripti ┆ … ┆ parameter ┆ input_fea ┆ input_fea ┆ creation │
│ d         ┆ ---       ┆ ---       ┆ on        ┆   ┆ s_json    ┆ ture_set_ ┆ tures_des ┆ _date    │
│ ---       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ id        ┆ cription  ┆ ---      │
│ str       ┆           ┆           ┆ str       ┆   ┆ str       ┆ ---       ┆ ---       ┆ date     │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ v1dd_1196 ┆ v1dd_r84_ ┆ V1DD r84  ┆ The qc_no ┆ … ┆ {"source_ ┆ null      ┆ QC-nonnul ┆ null     │
│           ┆ qc_nonnul ┆ QC-nonnul ┆ nnull_emb ┆   ┆ columns": ┆           ┆ l axon/de ┆          │
│           ┆ l_umap    ┆ l UMAP    ┆ ed0/1     ┆   ┆ ["qc_nonn ┆           ┆ ndrite    ┆          │
│           ┆           ┆           ┆ coordi…   ┆   ┆ ul…       ┆           ┆ featu…    ┆          │
│ v1dd_1196 ┆ v1dd_r84_ ┆ V1DD r84  ┆ The ad_re ┆ … ┆ {"source_ ┆ null      ┆ Axon-dend ┆ null     │
│           ┆ ad_ref_um ┆ axon-dend ┆ f_embed0/ ┆   ┆ columns": ┆           ┆ rite      ┆          │
│           ┆ ap        ┆ rite      ┆ 1 coordin ┆   ┆ ["ad_ref_ ┆           ┆ reference ┆          │
│           ┆           ┆ referen…  ┆ ate…      ┆   ┆ em…       ┆           ┆ featur…   ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

shape: (5, 5)
┌────────────┬────────────────────┬──────────────────────────┬──────────┬───────────┐
│ project_id ┆ dataitem_id        ┆ embedding_space          ┆ x        ┆ y         │
│ ---        ┆ ---                ┆ ---                      ┆ ---      ┆ ---       │
│ str        ┆ str                ┆ str                      ┆ f64      ┆ f64       │
╞════════════╪════════════════════╪══════════════════════════╪══════════╪═══════════╡
│ v1dd_1196  ┆ 864691132831533732 ┆ v1dd_r84_qc_nonnull_umap ┆ 0.345442 ┆ -1.792807 │
│ v1dd_1196  ┆ 864691132949445450 ┆ v1dd_r84_qc_nonnull_umap ┆ 6.055111 ┆ 14.027972 │
│ v1dd_1196  ┆ 864691132958976541 ┆ v1dd_r84_qc_nonnull_umap ┆ 3.275342 ┆ 9.773444  │
│ v1dd_1196  ┆ 864691132683159492 ┆ v1dd_r84_qc_nonnull_umap ┆ -1.15514 ┆ -2.168531 │
│ v1dd_1196  ┆ 864691132624495256 ┆ v1dd_r84_qc_nonnull_umap ┆ 1.597967 ┆ 3.562651  │
└────────────┴────────────────────┴──────────────────────────┴──────────┴───────────┘

shape: (5, 5)
┌────────────┬────────────────────┬──────────────────────┬───────────┬───────────┐
│ project_id ┆ dataitem_id        ┆ embedding_space      ┆ x         ┆ y         │
│ ---        ┆ ---                ┆ ---                  ┆ ---       ┆ ---       │
│ str        ┆ str                ┆ str                  ┆ f64       ┆ f64       │
╞════════════╪════════════════════╪══════════════════════╪═══════════╪═══════════╡
│ v1dd_1196  ┆ 864691132949445450 ┆ v1dd_r84_ad_ref_umap ┆ 2.862342  ┆ 13.20245  │
│ v1dd_1196  ┆ 864691132683159492 ┆ v1dd_r84_ad_ref_umap ┆ -0.038844 ┆ -4.722876 │
│ v1dd_1196  ┆ 864691132624495256 ┆ v1dd_r84_ad_ref_umap ┆ -2.0359   ┆ 1.671162  │
│ v1dd_1196  ┆ 864691132620003003 ┆ v1dd_r84_ad_ref_umap ┆ 2.735242  ┆ 14.169513 │
│ v1dd_1196  ┆ 864691132801183590 ┆ v1dd_r84_ad_ref_umap ┆ 1.184313  ┆ 16.24984  │
└────────────┴────────────────────┴──────────────────────┴───────────┴───────────┘

shape: (5, 11)
┌────────────┬─────────────┬────────────┬────────────┬───┬────────────┬────────────┬───────┬───────┐
│ project_id ┆ id          ┆ descriptio ┆ connectome ┆ … ┆ measuremen ┆ modality   ┆ value ┆ unit  │
│ ---        ┆ ---         ┆ n          ┆ _id        ┆   ┆ t_type     ┆ ---        ┆ ---   ┆ ---   │
│ str        ┆ str         ┆ ---        ┆ ---        ┆   ┆ ---        ┆ str        ┆ f64   ┆ str   │
│            ┆             ┆ str        ┆ str        ┆   ┆ str        ┆            ┆       ┆       │
╞════════════╪═════════════╪════════════╪════════════╪═══╪════════════╪════════════╪═══════╪═══════╡
│ v1dd_1196  ┆ v1dd_1196_v ┆ null       ┆ v1dd_1196_ ┆ … ┆ SYNAPSE_CO ┆ ELECTRON_M ┆ 30.0  ┆ COUNT │
│            ┆ 1dd_1196_em ┆            ┆ em_proofre ┆   ┆ UNT        ┆ ICROSCOPY  ┆       ┆       │
│            ┆ _proofre…   ┆            ┆ ad_axon_to ┆   ┆            ┆            ┆       ┆       │
│            ┆             ┆            ┆ …          ┆   ┆            ┆            ┆       ┆       │
│ v1dd_1196  ┆ v1dd_1196_v ┆ null       ┆ v1dd_1196_ ┆ … ┆ SYNAPSE_CO ┆ ELECTRON_M ┆ 2.0   ┆ COUNT │
│            ┆ 1dd_1196_em ┆            ┆ em_proofre ┆   ┆ UNT        ┆ ICROSCOPY  ┆       ┆       │
│            ┆ _proofre…   ┆            ┆ ad_axon_to ┆   ┆            ┆            ┆       ┆       │
│            ┆             ┆            ┆ …          ┆   ┆            ┆            ┆       ┆       │
│ v1dd_1196  ┆ v1dd_1196_v ┆ null       ┆ v1dd_1196_ ┆ … ┆ SYNAPSE_CO ┆ ELECTRON_M ┆ 1.0   ┆ COUNT │
│            ┆ 1dd_1196_em ┆            ┆ em_proofre ┆   ┆ UNT        ┆ ICROSCOPY  ┆       ┆       │
│            ┆ _proofre…   ┆            ┆ ad_axon_to ┆   ┆            ┆            ┆       ┆       │
│            ┆             ┆            ┆ …          ┆   ┆            ┆            ┆       ┆       │
│ v1dd_1196  ┆ v1dd_1196_v ┆ null       ┆ v1dd_1196_ ┆ … ┆ SYNAPSE_CO ┆ ELECTRON_M ┆ 1.0   ┆ COUNT │
│            ┆ 1dd_1196_em ┆            ┆ em_proofre ┆   ┆ UNT        ┆ ICROSCOPY  ┆       ┆       │
│            ┆ _proofre…   ┆            ┆ ad_axon_to ┆   ┆            ┆            ┆       ┆       │
│            ┆             ┆            ┆ …          ┆   ┆            ┆            ┆       ┆       │
│ v1dd_1196  ┆ v1dd_1196_v ┆ null       ┆ v1dd_1196_ ┆ … ┆ SYNAPSE_CO ┆ ELECTRON_M ┆ 4.0   ┆ COUNT │
│            ┆ 1dd_1196_em ┆            ┆ em_proofre ┆   ┆ UNT        ┆ ICROSCOPY  ┆       ┆       │
│            ┆ _proofre…   ┆            ┆ ad_axon_to ┆   ┆            ┆            ┆       ┆       │
│            ┆             ┆            ┆ …          ┆   ┆            ┆            ┆       ┆       │
└────────────┴─────────────┴────────────┴────────────┴───┴────────────┴────────────┴───────┴───────┘